# Generated by Django 5.0 on 2023-12-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Athlete",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("nationality", models.CharField(max_length=20)),
                ("currentRank", models.IntegerField()),
                ("sport", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("earnings", models.FloatField()),
            ],
        ),
    ]
